
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# \uC6B4\uC601\uC740 HTTPS \uC0AC\uC6A9
server.servlet.session.cookie.secure=true

# Reverse Proxy
server.forward-headers-strategy=native

server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

# \uC2E4\uC81C \uC6B4\uC601 \uD504\uB85D\uC2DC \uC8FC\uC18C\uB9CC \uC2E0\uB8B0\uD558\uB3C4\uB85D \uC124\uC815
server.tomcat.remoteip.internal-proxies=${INTERNAL_PROXIES}