spring.application.name=test01

# 1. PostgreSQL 연결 정보 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=kimjoowan!

# 2. JPA 방언 설정 (접속 실패 시 멈추는 에러 방지)
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 3. MyBatis 설정
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Thymeleaf 의존성이 캐시에 남은 경우를 대비
spring.thymeleaf.enabled=false