spring.application.name=test01
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 0.스프링 부트 배너 끄기
spring.main.banner-mode=off

# 1. PostgreSQL 연결 정보 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 3. MyBatis 설정
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Thymeleaf 의존성이 캐시에 남은 경우를 대비
spring.thymeleaf.enabled=false

# 운영 서버 배포 시에는 이 값을 더 길고 복잡한 난수로 변경하여 서버 환경변수로 주입하세요.
myapp.security.pepper=${PASSWORD_PEPPER}

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-binding-errors=never